s1="Universal"
print(type(s1))
print(id(s1))
print(s1)
print(s1*2)
print(s1 + "Indore")
print('Uni' in s1)
print('Uni' not in s1)
print(s1[0])
print(s1[1])
print(s1[2])
print(s1[3])
#print("Backward")
print(s1[-1])
print(s1[-2])
print(s1[-3])
print(s1[-4])
